# Generated by Django 4.2.5 on 2023-09-14 05:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant", "0002_alter_booking_comment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="booking",
            old_name="quest_number",
            new_name="guest_number",
        ),
    ]
