# Generated by Django 4.2.5 on 2023-09-14 05:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant", "0003_rename_quest_number_booking_guest_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menu",
            name="description",
            field=models.CharField(default="", max_length=1000),
        ),
    ]
